### PR TITLE
Create cn.josn

### PR DESCRIPTION
**Pull request by JNjiaonang**
添加了简体中文翻译

### CODE REVIEW

**Comment by JNjiaonang** [comment]
I am using it on my server, everything is fine, and the translation is completely correct

**Comment by Maximus7474** [comment]
Hi @JNjiaonang 

If your still up for it you can update your file with the new locale keys in the current [`en.json`](https://github.com/lbphone/lb-phone-locales/blob/main/en.json)

**Comment by Maximus7474** [comment]
This PR is over a year old now.
We thank you for your contribution but will be closing it.

**Comment by JNjiaonang** [comment]
I have been on vacation recently and may resubmit when I finish my vacation，

**Pull request closed without merging**
