### PR TITLE
Application translations into Spanish

### PR DESCRIPTION
**Pull request by lush0n3**

### CODE REVIEW

**Comment by brezedc** [comment]
Hey,  you're missing some updates from the latest update, please add them. (Check the most recent commit on en.lua to see the changes.)

**Comment by brezedc** [comment]
Hey, Just pushed one more update, please translate it! https://github.com/brezedc/lb-phone-locales/commit/115e288f7eda301c0155554573b913d281cb0a3e

**Comment by lush0n3** [comment]
updated

**Comment by brezedc** [comment]
There's a new update for the locales, sorry!

**Pull request closed without merging**
