### PR TITLE
Update fr.json for better translation and orthographic corrections

### PR DESCRIPTION
**Pull request by rahil-f**

### CODE REVIEW

**Comment by brezedc** [comment]
https://gyazo.com/f33f0426d8b27ee661593c2bfffe7609 Minor issue, please review the code.

**Comment by brezedc** [comment]
Needs to be updated to the latest version, missing translations.

**Comment by rahil-f** [comment]
update done by my side

**Comment by brezedc** [comment]
Hey, Just pushed one more update, please translate it! https://github.com/brezedc/lb-phone-locales/commit/115e288f7eda301c0155554573b913d281cb0a3e

**Comment by rahil-f** [comment]
Updated with the translate of the new update [115e288](https://github.com/brezedc/lb-phone-locales/commit/115e288f7eda301c0155554573b913d281cb0a3e) @brezedc

**Comment by rahil-f** [comment]
Any News?

**Comment by brezedc** [comment]
Outdated, just merged a up-to-date french translation, please correct any mistakes on that one and I'll merge it asap!

**Pull request closed without merging**
