### PR TITLE
added "notifications_popup"

### PR DESCRIPTION
**Pull request by xmxf-pro**

### CODE REVIEW

**Comment by brezedc** [comment]
Hey, Just pushed one more update, please translate it! https://github.com/brezedc/lb-phone-locales/commit/115e288f7eda301c0155554573b913d281cb0a3e

**Comment by xmxf-pro** [comment]
Done

**Comment by brezedc** [comment]
Updated again, sorry!

**Comment by brezedc** [comment]
Just merged a more up-to-date version.

**Pull request closed without merging**
